import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/layouts/header/Header";
import Footer from "./components/layouts/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja" style={{ backgroundColor: "var(--sub6)" }}>
      <Header />
      <body>{children}</body>
      {/* <Footer/> */}
    </html>
  );
}
